class ReasoningAgent:
    def __init__(self):
        self.disclaimer = "This report is generated by AI for informational purposes only. It is NOT a professional medical diagnosis or prescription. Always consult with a qualified healthcare professional regarding any medical concerns or conditions."

    async def summarize(self, risk_data, clinical_entities, biomedical_tags):
        # In a real-world scenario, this might call a LLM like GPT-4 or Gemini
        # for a more natural summary. Here we provide a structured rule-based summary.
        
        risk_level = risk_data.get("risk_level", "Unknown")
        confidence = risk_data.get("confidence_score", 0.0)
        
        explanation = f"Based on the clinical analysis, the estimated risk level for the provided report is {risk_level} (Confidence: {confidence:.2%}). "
        
        # Add highlights from Medspacy
        if clinical_entities:
            top_entities = [e["text"] for e in clinical_entities[:3]]
            explanation += f"Key clinical markers identified include: {', '.join(top_entities)}. "
            
        # Add negations if any
        negated = [e["text"] for e in clinical_entities if e.get("is_negated")]
        if negated:
            explanation += f"The system noted the absence or negation of: {', '.join(negated[:3])}. "

        explanation += "\nPlease review these findings with your doctor for a definitive interpretation."

        return {
            "explanation": explanation,
            "disclaimer": self.disclaimer
        }
